adding error handling for sphinx file

diff --git a/.github/workflows/ci-sphinx.yaml b/.github/workflows/ci-sphinx.yaml
--- a/.github/workflows/ci-sphinx.yaml
+++ b/.github/workflows/ci-sphinx.yaml
@@ -18,11 +18,13 @@ jobs:
           pip install -r requirements.txt
       - name: Build HTML documentation
         run: |
-          sphinx-apidoc -o docs/source/ sample/
+          sphinx-apidoc -o docs/source/ sample/ || { echo "sphinx-apidoc command failed"; exit 1; }
           cd docs
-          make html
-          cd build
-          zip ../../api_docs.zip -r html/
+          make html || { echo "Sphinx documentation build failed"; exit 1; }
+      - name: Archive HTML documentation
+        run: |
+          cd source/build/html
+          zip -r ../../../api_docs.zip . || { echo "Zipping documentation failed"; exit 1; }
       - name: Upload html documentation
         uses: actions/upload-artifact@v2
         with:
